// Generated by SOL v0.4.2.1
#include <sol/kernel.h>
#include <stdint.h>
#include "libFlexMLP.h"
#include "../../ve/src/ve_9BC88669.h"

static int s_initialized = 0;
static Params s_params;
extern const void* _binary_libFlexMLP_F0_Output_start;
extern const void* _binary_libFlexMLP_F1_Output_start;
extern const void* _binary_libFlexMLP_F2_Output_start;
extern const void* _binary_libFlexMLP_F3_Output_start;
extern const void* _binary_libFlexMLP_F4_Output_start;
extern const void* _binary_libFlexMLP_F5_Output_start;

extern void ve_9BC88669_create(sol_ctx* ctx);
extern void ve_9BC88669_FI(sol_ctx* ctx);

static void forward_init(void) {
	if(!s_initialized) {
		s_initialized = 1;
		s_params.F0_Output.ref = (void*)&_binary_libFlexMLP_F0_Output_start;
		s_params.F1_Output.ref = (void*)&_binary_libFlexMLP_F1_Output_start;
		s_params.F2_Output.ref = (void*)&_binary_libFlexMLP_F2_Output_start;
		s_params.F3_Output.ref = (void*)&_binary_libFlexMLP_F3_Output_start;
		s_params.F4_Output.ref = (void*)&_binary_libFlexMLP_F4_Output_start;
		s_params.F5_Output.ref = (void*)&_binary_libFlexMLP_F5_Output_start;
	}
}

void forward(void* user_data, const double* F6_Output, double* F15_Output) {
	Inputs inputs;
	inputs.F6_Output.ref = (void*)F6_Output;
	Outputs outputs;
	outputs.F15_Output.ref = (void*)F15_Output;
	sol_ctx ctx;
	ctx.inputs     = (sol_tensor*)&inputs;
	ctx.outputs    = (sol_tensor*)&outputs;
	ctx.params     = (sol_tensor*)&s_params;
	ctx.batch_size = 0;
	ctx.device_idx = 0;
	if(!s_initialized) {
		forward_init();
	}

	ve_9BC88669_create(&ctx);
	ve_9BC88669_FI(&ctx);
}
